<!-- jQuery Plugins -->
		<script src="{{ asset('frontend/js/jquery.min.js') }}"></script>
		<script src="{{ asset('frontend/js/bootstrap.min.js') }}"></script>
		<script src="{{ asset('frontend/js/slick.min.js') }}"></script>
		<script src="{{ asset('frontend/js/nouislider.min.js') }}"></script>
		<script src="{{ asset('frontend/js/jquery.zoom.min.js') }}"></script>
		<script src="{{ asset('frontend/js/main.js') }}"></script>
		<!-- SweetAlert2 JS -->
		<script src="{{ asset('backend/assets/js/sweetalert2.min.js' )}}"></script>
		<script src="{{ asset('backend/assets/js/sweetalert2.all.min.js' )}}"></script>